google-modules: soc: Eliminate VLA in s3c2410wdt_print_schedstat
This resolves the following compilation error:

../google-modules/soc/gs/drivers/watchdog/s3c2410_wdt.c: In function 's3c2410wdt_print_schedstat':
../google-modules/soc/gs/drivers/watchdog/s3c2410_wdt.c:723:9: error: ISO C90 forbids variable length array 'buf' [-Werror=vla]
  723 |         char buf[max(NR_CPUS, PRINT_CPUS_LIMIT)];
      |         ^~~~

The max() macro evaluates to a variable-length array (VLA), which is not
allowed in ISO C90. Since PRINT_CPUS_LIMIT (30) is already larger than
CONFIG_NR_CPUS (8) on this platform, we can use PRINT_CPUS_LIMIT directly
as a compile-time constant.

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>